apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: spark-cluster
  region: us-east-1
  version: "1.13"

nodeGroups:

  - name: spark-nodes
    instanceType: m5.xlarge
    volumeSize: 30
    desiredCapacity: 4
    minSize: 1
    maxSize: 4
    privateNetworking: true
    maxPodsPerNode: 10